apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "api-v3.fullname" . }}-web-sockets-config
  labels:
    app: {{ template "api-v3.name" . }}
    chart: {{ template "api-v3.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yaml: |
    port: 80
    version: {{ $.Values.servicesSettings.webSockets.tag }}

    logSettings:
      level: debug
      format: {{ $.Values.commonSettings.logsFormat }} # 1 - simple, 2 - json
      colorize: true

    rabbitmq: 
      url: {{ $.Values.rabbitmq.url }}
      exchange: {{ $.Values.rabbitmq.exchange }}
      queuesDurable: false
      autoDeleteQueues: true
