apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "api-v3.fullname" . }}-fake-sessions-config
  labels:
    app: {{ template "api-v3.name" . }}
    chart: {{ template "api-v3.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.yaml: |        
    port: 80
    version: {{ $.Values.servicesSettings.fakeSessions.tag }}

    reqGuidHeader: 'request-id'
    defaultLimit: 100

    logSettings:
      level: {{ $.Values.commonSettings.logsLevel }}
      format: {{ $.Values.commonSettings.logsFormat }} # 1 - simple, 2 - json
      colorize: true

    dbSettings:
      notEnabled: true
      host: ''
      user: ''
      password: ''
      port: ''
      connectionLimit: {{ $.Values.commonSettings.connectionLimit }}

    relationships:

    users:
      - username: "john.doe"
        password: "as$drf%gyt"     
      - username: "julia.simpson"
        password: "Jhg&fd$s34"  
      - username: "michael.robirtson"
        password: "fGd5Sqw^hg9"        
      - username: "clara.edington"
        password: "nYft$d6s@45"  
      - username: "james.weel"
        password: "oi$d@23Rf&a" 
      - username: "vladimir.ermolaev"
        password: 'asd123' 
      - username: "brooke.williams"
        password: "asd123" 
      - username: "galina.donovan"
        password: "v"         
      - username: "nadia.naoumoff"
        password: "asd123"  
      - username: "stephen.tancik"
        password: "asd123"  
      - username: "bricklend.ward"
        password: "asd123"  
      - username: "brian.rodriguez"
        password: "asd123"  
      - username: "maria.bendiola"
        password: "asd123"      
      - username: "alex.degtiarev"
        password: "asd123"  
      - username: "benjamin.ang"
        password: "asd123"                                      
        
    resources:
      -    
        name: 'sessions'
        prefix: 'sessions' 
        methods: [ 'GET', 'POST', 'DELETE' ]
        tables:
          mainTable: ''
          actionTable: ''           