kind: Secret
apiVersion: "v1"
metadata:
  name: database-credentials
data:
  dbHost: {{ .Values.dbSettings.host | b64enc }}
  dbUser: {{ .Values.dbSettings.user | b64enc }}
  dbPassword: {{ .Values.dbSettings.password | b64enc }}
